part2_django/hw10_django/hw10_django/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('quotes.urls')),
    path('users/', include('users.urls')),
]

part2_django/hw10_django/quotes/urls.py
from django.urls import path

from . import views

app_name = "quotes"
urlpatterns = [
    path('', views.home, name='home'),
    path('<int:page>', views.home, name='root_paginate'),
    path('author/<int:_id>', views.author_about, name='author_about'),
    path('add_author/', views.add_author, name='add_author'),
    path('add_quote/', views.add_quote, name='add_quote'),
    path('add_tag/', views.add_tag, name='add_tag'),
    path('tag/<int:_id>/', views.find_tag, name='find_tag'),
    path('tag/<str:_id>/', views.find_tag, name='find_tag'),
]

part2_django/hw10_django/users/urls.py
from django.urls import path
from django.contrib.auth.views import LoginView, LogoutView, PasswordResetDoneView, PasswordResetConfirmView, \
    PasswordResetCompleteView
from .views import RegisterView
from .forms import LoginForm
from . import views

app_name = "users"

urlpatterns = [
    path('signup/', RegisterView.as_view(), name='register'),
    path('login/', LoginView.as_view(
        template_name="users/login.html",
        authentication_form=LoginForm,
        redirect_authenticated_user=True
    ), name='login'),
    path('logout/', LogoutView.as_view(
        template_name="users/logout.html",
    ), name='logout'),
    path('reset-password/', views.ResetPasswordView.as_view(), name='password_reset'),
    path('reset-password/done/', PasswordResetDoneView.as_view(template_name='users/password_reset_done.html'),
         name='password_reset_done'),
    path('reset-password/confirm/<uidb64>/<token>/',
         PasswordResetConfirmView.as_view(template_name='users/password_reset_confirm.html',
                                          success_url='/users/reset-password/complete/'),
         name='password_reset_confirm'),
    path('reset-password/complete/',
         PasswordResetCompleteView.as_view(template_name='users/password_reset_complete.html'),
         name='password_reset_complete'),
]

part2_django/hw10_django/quotes/models.py
from django.db import models


# Create your models here.
class Author(models.Model):
    fullname = models.CharField(max_length=50)
    born_date = models.CharField(max_length=50)
    born_location = models.CharField(max_length=100)
    description = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"{self.fullname}"


class Tag(models.Model):
    name = models.CharField(max_length=50, null=False, unique=True)

    def __str__(self):
        return f"{self.name}"


class Quote(models.Model):
    author = models.ForeignKey(Author, on_delete=models.CASCADE, default=None, null=True)
    tags = models.ManyToManyField(Tag)
    quote = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"{self.quote}"

part2_django/hw10_django/quotes/forms.py
from django.forms import ModelForm, CharField, TextInput, DateField, SelectMultiple, \
    ModelChoiceField, Select, ModelMultipleChoiceField
from .models import Author, Quote, Tag


class AuthorForm(ModelForm):
    fullname = CharField(max_length=50, required=True, widget=TextInput(attrs={"class": "form-control"}))
    born_date = DateField(widget=TextInput(attrs={"class": "form-control"}))
    born_location = CharField(max_length=200, required=True, widget=TextInput(attrs={"class": "form-control"}))
    description = CharField(required=True, widget=TextInput(attrs={"class": "form-control"}))

    class Meta:
        model = Author
        fields = ['fullname', 'born_date', 'born_location', 'description']


class QuoteForm(ModelForm):
    quote = CharField(required=True, widget=TextInput(attrs={"class": "form-control"}))
    tags = ModelMultipleChoiceField(queryset=Tag.objects.all().order_by('name'),
                                    widget=SelectMultiple(attrs={'class': 'form_control', 'size': 10}))
    author = ModelChoiceField(queryset=Author.objects.all().order_by('fullname'),
                              widget=Select(attrs={"class": "form-control"}))

    class Meta:
        model = Quote
        fields = ['quote', 'tags', 'author']


class TagForm(ModelForm):
    name = CharField(max_length=50, required=True, widget=TextInput(attrs={"class": "form-control"}))

    class Meta:
        model = Tag
        fields = ['name']

part2_django/hw10_django/quotes/views.py
from django.core.paginator import Paginator
from django.db.models import Count
from django.shortcuts import redirect, render
from django.contrib.auth.decorators import login_required

from .models import Author, Quote, Tag

from .forms import AuthorForm, QuoteForm, TagForm


def home(request, page=1):
    quotes = Quote.objects.all()
    per_page = 10
    paginator = Paginator(list(quotes), per_page)
    quotes_on_page = paginator.page(page)
    top_tags = Quote.objects.values('tags__name').annotate(quote_count=Count('tags__name')).order_by('-quote_count')[
               :10]
    return render(request, "quotes/index.html", context={"quotes": quotes_on_page, 'top_tags': top_tags})


def author_about(request, _id):
    author = Author.objects.get(pk=_id)
    return render(request, 'quotes/author.html', context={'author': author})


@login_required
def add_quote(request):
    if request.method == 'POST':
        form = QuoteForm(request.POST)
        if form.is_valid():
            new_quote = form.save()
            return redirect(to='quotes:home')
        else:
            return render(request, 'quotes/add_quote.html',
                          context={'form': form, 'message': "Incorrect form"})
    return render(request, 'quotes/add_quote.html', context={'form': QuoteForm()})


@login_required
def add_author(request):
    if request.method == 'POST':
        form = AuthorForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect(to='quotes:home')
        else:
            return render(request, 'quotes/add_author.html',
                          context={'form': AuthorForm, 'message': "Форма невірна"})
    return render(request, 'quotes/add_author.html', context={'form': AuthorForm()})


@login_required
def add_tag(request):
    if request.method == 'POST':
        form = TagForm(request.POST)
        if form.is_valid():
            new_tag = form.save()
            return redirect(to='quotes:home')
        else:
            return render(request, 'quotes/add_tag.html',
                          context={'form': TagForm, 'message': "Incorrect form"})
    return render(request, 'quotes/add_tag.html', context={'form': TagForm})


def find_tag(request, _id):
    per_page = 10
    if isinstance(_id, int):
        quotes = Quote.objects.filter(tags=_id).all()
    elif isinstance(_id, str):
        tag_id = Tag.objects.filter(name=_id).first()
        quotes = Quote.objects.filter(tags=tag_id).all()
    paginator = Paginator(list(quotes), per_page)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    top_tags = Quote.objects.values('tags__id', 'tags__name').annotate(quote_count=Count('tags__name')).order_by(
        '-quote_count')[:10]

    return render(request, 'quotes/find_tag.html',
                  context={'quotes': page_obj, 'tag_name': _id, 'top_tags': top_tags})

part2_django/hw10_django/quotes/templates/quotes/add_author.html
{%extends "quotes/base.html"%}

{% block content %}
<h3>Add Author</h3>

{%if form.errors %}
<span class="alert alert-danger" role="alert">{{form.non_field_errors}}</span>
{% endif %}

<form method="post">
    {% csrf_token %}
    <div class="row mb-3 col-md-6">
        <label>Author</label>
        {{form.fullname}}
    </div>
    <div class="row mb-3 col-md-6">
        <label class="form-label">Born date</label>
        {{form.born_date}}
    </div>
    <div class="row mb-3 col-md-6">
        <label>Born location</label>
        {{form.born_location}}
    </div>
      <div class="row mb-3 col-md-6">
        <label>Description</label>
        {{form.description}}
    </div>


    <button type="submit" class="btn btn-primary">Add author</button>
</form>
{% endblock %}

part2_django/hw10_django/quotes/templates/quotes/add_quote.html
{%extends "quotes/base.html"%}

{% block content %}
<h3>Add a quote</h3>

{%if form.errors %}
<span class="alert alert-danger" role="alert">{{form.non_field_errors}}</span>
{% endif %}

<form method="post">
<!--    action="{% url 'quotes:add_quote' %}"-->
    {% csrf_token %}
    <div class="row mb-3 col-md-6">
        <label>quote</label>
        {{form.quote}}
    </div>
    <div class="row mb-3 col-md-6">
        <label class="form-label">Tags</label>
        {{form.tags}}
    </div>
    <div class="row mb-3 col-md-6">
        <label>Author</label>
        {{form.author}}
    </div>
    <button type="submit" class="btn btn-primary">Add a quote</button>
</form>
{% endblock %}

part2_django/hw10_django/quotes/templates/quotes/add_tag.html
{% extends "quotes/base.html" %}

{% block content %}
<h3>Add tag</h3>

{% if form.errors %}
<span class="alert alert-danger" role="alert">{{ form.non_field_errors }}</span>
{% endif %}

<form method="post">
    {% csrf_token %}
    <div class="row mb-3 col-md-6">
        <label class="form-label">Tag</label>
        {{ form.name }}
    </div>
    <button type="submit" class="btn btn-primary">Submit</button>
</form>

{% endblock %}

part2_django/hw10_django/quotes/templates/quotes/author.html
{% extends "quotes/base.html" %}
{% load extract %}

{% block content %}
<div class="author-details">
    <h3 class="author-title">{{ author.fullname }}</h3>
    <p><strong>Born:</strong> <span class="author-born-date">{{ author.born_date }}</span> <span
            class="author-born-location">{{ author.born_location }}</span></p>
    <p><strong>Description:</strong></p>
    <div class="author-description">{{ author.description }}</div>
</div>

{% endblock %}

part2_django/hw10_django/quotes/templates/quotes/base.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, initial-scale=1.0">

    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/css/bootstrap.min.css"
          integrity="sha384-KK94CHFLLe+nY2dmCWGMq91rCGa5gtU4mk92HdvYe+M/SXH301p5ILy+dN9+nJOZ" crossorigin="anonymous">

    {% load static %}
    <link rel="icon" type="image/png" sizes="16x16" href="{% static 'quotes/img/img.png'%}">
    <link rel="stylesheet" href="{% static 'quotes/style.css' %}">
    <title>{{ title }}</title>
</head>
<body>

<nav class="navbar navbar-expand-lg navbar-dark bg-primary mb-3">
    <div class="container-fluid">
        <a class="navbar-brand" href="/" style="font-size: 1.5rem; color: #fff;">Quotes to Scrape</a>

        {% if user.is_authenticated %}
        <p class="mb-0 me-2 ps-3 text-light">Welcome, {{user.username}}</p>
        <div class="d-flex justify-content-between align-items-center">
            <a class="btn btn-outline-light me-2" href="{% url 'quotes:add_quote' %}">Add quote</a>
            <a class="btn btn-outline-light me-2" href="{% url 'quotes:add_author' %}">Add author</a>
            <a class="btn btn-outline-light me-2" href="{% url 'quotes:add_tag' %}">Add tag</a>
            <a class="btn btn-outline-light" href="{% url 'users:logout' %}">SignOut</a>
        </div>
        {% else %}
        <div class="d-flex justify-content-between align-items-center">
            <a class="btn btn-outline-light me-2" href="{% url 'users:register' %}">SignUp</a>
            <a class="btn btn-outline-light" href="{% url 'users:login' %}">LogIn</a>
        </div>
        {% endif %}

        {% if request.user.is_superuser %}
        <div class="d-flex justify-content-between align-items-center">
            <a class="btn btn-outline-danger me-2" href="{% url 'quotes:parse' %}">Quotes parsing</a>
        </div>
        {% endif %}
    </div>
</nav>

<div class="container mb-5">
    {% block content %}

    {% endblock %}
</div>

<!--<footer class="bg-secondary text-center py-2 fixed-bottom">-->
<!--    <p>© Quotes. Created by <a class="text-info mb-0" href="https://github.com/dragomar14/WEB-HW-10">Dmytro Marchenko</a>-->
<!--        <script class="text-light">document.write(new Date().getFullYear())</script>-->
<!--    </p>-->
<!--</footer>-->

<!--<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/js/bootstrap.bundle.min.js"-->
<!--        integrity="sha384-r6IvZ35Kj41FWP63M0uJw4Ov7xW0E8Y9/lbmcS5SdWeKjPpI8irTWVgJ4mfwvmyV"-->
<!--        crossorigin="anonymous"></script>-->

</body>
</html>

part2_django/hw10_django/quotes/templates/quotes/find_tag.html
{%extends "quotes/base.html"%}
{% load extract %}

{% block content %}
<div class="row">
    <div class="col-md-8">
        {% for quote in quotes %}
        <div class="quote" itemscope="" itemtype="http://schema.org/CreativeWork">
            <span class="text" itemprop="text">{{quote.quote}}</span>
            <span>by <small class="author" itemprop="author">{{quote.author.fullname}}</small>
            <a href="{% url 'quotes:author_about' quote.author.id %}">(about)</a>
            </span>
            <div class="tags">
                Tags:
                {% for tag in quote.tags.all %}
                <a class="tag" href="{% url 'quotes:find_tag' tag.id %}">{{tag.name}}</a>
                {% endfor %}
            </div>
        </div>
        {% endfor %}
        <nav>
           <ul class="pagination">
                <li class="previous">
                    <a class="{% if not quotes.has_previous %} disabled {% endif %}"
                   href="{% if quotes.has_previous %} {% url 'quotes:root_paginate' quotes.previous_page_number %} {% else %} # {% endif %}">
                    <span aria-hidden="true">←</span> Previous</a>
                </li>
                <li class="current">
                    Page {{ quotes.number }} of {{ quotes.paginator.num_pages }}
                </li>
                <li class="next">
                    <a class="{% if not quotes.has_next %} disabled {% endif %}"
                   href="{% if quotes.has_next %} {% url 'quotes:root_paginate' quotes.next_page_number %} {% else %} # {% endif %}">Next
                    <span aria-hidden="true">→</span></a>
                </li>

            </ul>
        </nav>
    </div>
    <div class="col-md-4 themed-grid-col">
        <h2>Top 10 Tags</h2>
        {% for tag in top_tags %}
        <div class="tags" style="margin-bottom: 10px;">
            <a class="btn btn-info" href="{% url 'quotes:find_tag' tag.tags__name %}">{{tag.tags__name}}</a>
        </div>
        {% endfor %}
    </div>
</div>
{% endblock %}

part2_django/hw10_django/quotes/templates/quotes/index.html
{%extends "quotes/base.html"%}
{% load extract %}


{% block content %}
<div class="row">
    <div class="col-md-8 themed-grid-col">
        {% for quote in quotes %}
        <div class="quote" itemscope="" itemtype="http://schema.org/CreativeWork">
            <span class="text" itemprop="text">{{quote.quote}}</span>
            <span>by <small class="author" itemprop="author">{{quote.author.fullname}}</small>
        <a href="{% url 'quotes:author_about' quote.author.id %}">(about)</a>
        </span>
            <div class="tags">
                Tags:
                {% for tag in quote.tags.all %}
                <a class="tag" href="{% url 'quotes:find_tag' tag.id %}">{{tag.name}}</a>
                {% endfor %}
            </div>
        </div>
        {% endfor %}
        <nav>
            <ul class="pagination">
                <li class="previous">
                    <a class="{% if not quotes.has_previous %} disabled {% endif %}"
                   href="{% if quotes.has_previous %} {% url 'quotes:root_paginate' quotes.previous_page_number %} {% else %} # {% endif %}">
                    <span aria-hidden="true">←</span> Previous</a>
                </li>
                <li class="current">
                    Page {{ quotes.number }} of {{ quotes.paginator.num_pages }}
                </li>
                <li class="next">
                    <a class="{% if not quotes.has_next %} disabled {% endif %}"
                   href="{% if quotes.has_next %} {% url 'quotes:root_paginate' quotes.next_page_number %} {% else %} # {% endif %}">Next
                    <span aria-hidden="true">→</span></a>
                </li>

            </ul>
        </nav>

    </div>
    <div class="col-md-4 themed-grid-col">
        <h2>Top 10 Tags</h2>
        {% for tag in top_tags %}
        <div class="tags " style="margin-bottom: 10px;">
            <a class="btn btn-info" href="{% url 'quotes:find_tag' tag.tags__name %}">{{tag.tags__name}}</a>
        </div>
        {% endfor %}
    </div>
</div>
{% endblock %}